name: simplesearch
version: 1.0.0
grade: stable
summary: Just a test on generating a snap package for a Qt5 application
description: |
  Just a test on generating a snap package for a Qt5 application.
confinement: strict
base: core18

apps:
  simplesearch:
    command: /build/simplesearch/parts/simplesearch/install/bin/simplesearch

parts:
  simplesearch:
    source: .
    plugin: qmake
    qt-version: qt5
    project-files: [simplesearch.pro]
    build-packages:
      - qtbase5-dev
      - qttools5-dev
      - qttools5-dev-tools
      - libqt5x11extras5-dev
      - libqt5svg5-dev

